# Generated by Django 4.0.6 on 2022-08-23 12:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.TextField(blank=True, max_length=600)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='home',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
