# Generated by Django 4.0.6 on 2022-08-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_about_home_email_home_location_home_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='year_month',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill1',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
