# Generated by Django 4.0.6 on 2022-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_experience_title_alter_services_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
