# Generated by Django 4.0.6 on 2022-08-24 09:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_services_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('user_story', models.TextField(blank=True, max_length=500)),
                ('technologies', models.CharField(blank=True, max_length=40)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
