# Generated by Django 4.0.6 on 2022-08-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_allskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user_story1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projects',
            name='user_story2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projects',
            name='user_story3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projects',
            name='user_story4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projects',
            name='user_story5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projects',
            name='user_story6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='user_story',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
