# Generated by Django 4.0.6 on 2022-08-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_projects_user_story1_projects_user_story2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='documents')),
            ],
        ),
    ]
