# Generated by Django 4.0.6 on 2022-08-30 08:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_mycv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
