# Generated by Django 4.0.6 on 2022-08-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_mycv_certificate_alter_mycv_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achiev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField(blank=True)),
                ('projects', models.IntegerField(blank=True)),
                ('review', models.IntegerField(blank=True)),
                ('years', models.IntegerField(blank=True)),
            ],
        ),
    ]
