# Generated by Django 4.0.6 on 2022-09-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_achiev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user_story1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_story2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_story3',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_story4',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_story5',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_story6',
        ),
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='projects',
            name='user_story',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
